### ISSUE TITLE
Architecture Design Document - Developers lead this 

### ISSUE THREAD

**Issue by bryansturdivant** [COS420-Fall24/Team-F#52]
Architecture design (/10)  

Developers lead this

Examples: [Team C 2022](https://docs.google.com/document/d/1OG6txMwHzCfog6YLM_vxo4DIkhL-nvrx/edit) and [Team F 2022](https://docs.google.com/document/d/1xVi9zW4GadxJmQ8z1thv0pwIRkUIy-ZB3q2WFEO9JGQ/edit#heading=h.s6v4xgruuay5) (this has more detail and is closer to a detailed technical design, you don’t need to do this much)

This will most likely be a MVC architecture. You can use the examples or [this as a template](https://docs.google.com/document/d/1S7R3Tt6wKMN1nIgka4z8HZBGtxmpXdrA/edit), but your team will need to fill in your specific technologies and other information specific for your app. The example is for an online shopping system.

A UML package diagram showing the system architecture, where the basic classes/system entities are located, and associations. 

If the classes, associations, system architecture are not properly shown, deduct -7.5 points.

The name of the classes, packages, etc should match the application under the development. If not, deduct -2 points for each mismatch.

The description of the architecture and the justification of the chosen architecture.

If the description is missing or does not make sense, deduct -7.5 points. 

If the reason to choose this specific architecture does not make sense, deduct -7.5 points.

**Comment by izgebayyurt** [comment]
Check the architecture document here: https://docs.google.com/document/d/1dtw-3d20RLe5iDZJYv5ELDdYkEb1k8K6/edit#heading=h.ucppsjmrnwjm

**Comment by Noah-Moring** [comment]
To me this makes sense, I just can't tell if this is exactly what the rubric is asking for? I'd say it's a good start although I wouldn't be surprised if there's a bit of feedback left by Greg?!
