### ISSUE TITLE
New Version of App Implemented 

### ISSUE THREAD

**Issue by bryansturdivant** [COS420-Fall24/Team-F#54]
New version of the application (/10)

The implementation should have been started.  It is recommended to begin with the UI and some classes such as sign-up, login, etc. The developers should lead this and are expected to, as needed, review/complete parts of the [Interactive React Textbook](https://greglnelson.github.io/react-hooks-typescript-tome/) earlier than other team members, do self-directed learning using Google, StackOverflow, other online resources, and ask people or other classmates questions.

If there is no code/HTML/scripts, and no changes from last time, this part will be graded as 0.

As a reminder, review the class policies about copyright and AI use. You can even use code from prior projects to help start your project.

Setting up the build environments and the necessary dependencies.  

If there is nothing, deduct -5 points.

Your README file should detail the installation and build process for your application. Make sure it works on each person’s machine.

If there is nothing, deduct -5 points.

**Comment by izgebayyurt** [comment]
The build works, README is updated as necessary
