### ISSUE TITLE
Address feedback from previous deliverable

### ISSUE THREAD

**Issue by Noah-Moring** [COS420-Fall24/Team-F#77]

**Comment by Noah-Moring** [comment]
I believe everything has been double checked. The only thing left in terms of Revisions from Deliverable 1 is the SRS revisions. That should be handled and those are also tasks that are individually assigned to Izge.

**Comment by Noah-Moring** [comment]
Mis-clicked, accidentally closed this and then tried to bring it back to qc but github project automation doesn't let you do that. So I had to re-open, sorry!

**Comment by bryansturdivant** [comment]
I triple-checked, and I believe it looks good. I'll close this issue as the SRS feedback has it's own separate issue.
