### ISSUE TITLE
Product Backlog - Update

### ISSUE THREAD

**Issue by BoppleOpple** [COS420-Fall24/Team-F#79]
Product Backlog ( /5) 
- The comments from Deliverable 2 must be addressed.
  - For any comment that was not addressed, deduct -2 points. 
  - All unaddressed comments are carried forward by default to the next deliverable as well
-  All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.
- The backlog should have been updated with respect to sprint numbers, story points, etc.
- If there is no update, deduct -2.5 points.

**Comment by BoppleOpple** [comment]
@Noah-Moring I presume this is all set to be moved to QC since the sprint has started?

**Comment by Noah-Moring** [comment]
> [@Noah-Moring](https://github.com/Noah-Moring) I presume this is all set to be moved to QC since the sprint has started?

If nothing on the Product Backlog has changed then I can move it to QC yes. Eventually we will need to start pulling things from the Product Backlog and updating associated fields with each item.

**Comment by Noah-Moring** [comment]
Don't really think there was much to update on Product Backlog as of now. Things will get moving off of there soon.

**Comment by bryansturdivant** [comment]
Everything looks good!
