### ISSUE TITLE
Product Backlog - Address Feedback

### ISSUE THREAD

**Issue by BoppleOpple** [COS420-Fall24/Team-F#83]
Product Backlog ( /5) 
- The comments from Deliverable 2 must be addressed.
  - For any comment that was not addressed, deduct -2 points. 
  - All unaddressed comments are carried forward by default to the next deliverable as well
-  All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.
- The backlog should have been updated with respect to sprint numbers, story points, etc.
- If there is no update, deduct -2.5 points.

**Comment by BoppleOpple** [comment]
I may be wrong about this, but there doesn't seem to be any feedback. moving to QC for a second opinion

**Comment by Noah-Moring** [comment]
I also didn't find anything regarding feedback
