### ISSUE TITLE
Sprint Backlog - Update Sprint Backlog

### ISSUE THREAD

**Issue by BoppleOpple** [COS420-Fall24/Team-F#86]
Sprint Backlog 4 (/5) 
- The comments and feedback from the prior Deliverable must be addressed. 
  - For any comment that was not addressed, deduct -2 points.
- Contains only the stories (user stories and technical and non-technical stories) you commit to working on and delivering for prior Deliverable.  Should reflect the product backlog. That is, all the user stories that are assigned to Sprint 3 in the product backlog, should be shown in the Sprint Backlog 3.
  - For any missing user story, deduct -2 points.
  - If the Sprint Backlog 3 does not reflect the product backlog, deduct -5 points.
- You must have other technical tasks in your backlog otherwise -5.
- You must have other tasks in the backlog, like documentation, requirements, UI mockups, etc. As covered in class sessions, these are called non-technical stories. Otherwise -5.
- Sprint backlog must have accurate information about who did what % of the work. The sprint retrospective is a good time to fill that in, so you can see the difference between planned and actual effort.

**Comment by Noah-Moring** [comment]
Sprint Backlog should be updated, although some members still need to qc and add contribution %'s

Exported backlogs can be found here: https://drive.google.com/drive/folders/1x3imhf3NX7ccMkiC_o4LVYtU36HYmFAM?usp=drive_link

**Comment by BoppleOpple** [comment]
With the exception of Izge and Bryan (who might be asleep?) this seems to be taken care of. should I close this task?

**Comment by Noah-Moring** [comment]
Yeah go ahead and close it. They can address those things in the morning, it's not urgent
