### ISSUE TITLE
Domain Model - Complete

### ISSUE THREAD

**Issue by A-McGlauflin** [COS420-Fall24/Team-F#89]
Submit a model of the domain with links and relationships. The expectation is that you have at least 8 classes in their diagram. If your domain is actually very small, you may have less.

        If the number of classes is below 8, per each missing class -2.5 points.

    If the model is too large, break it down in to 2 – 4 smaller models.

        Otherwise, -5 points overall.

    UML domain model needs to include attributes, links, methods.

        For each mistake, -2 points.

        Create a task to compare your sequence diagrams and domain model and harmonize them (consistent method names)

        If the domain includes something like database or UI deduct -2 points per mistake.

        Links should be correct. If not, each mistake -2 points.

            Represents reasonable relationship

            Cardinality is reasonable (e.g. 0..* zero to many, …)
            
        Students also need to have a description for the domain model as a whole and how each smaller model is related to the rest.

    If the description is missing, deduct -10 points.

    If the description is not completed, deduct -5 points.

**Comment by BoppleOpple** [comment]
I checked this and responded with some edits in the discord, it looks great!
