### ISSUE TITLE
Add all the documents to a folder & check them in GitHub

### ISSUE THREAD

**Issue by izgebayyurt** [COS420-Fall24/Team-F#98]
Make sure to download these documents and check them into your Github repo as well in a folder Documentation/Deliverable3; this is also good practice in Industry as a backup. That is required and you will get -20 unrecoverable on the assignment if you do not do that. Include any documents you revised in that folder as well.

**Comment by Noah-Moring** [comment]
Should be in a folder on the repo, at least the documents for this deliverable specifically.

**Comment by BoppleOpple** [comment]
Should the Architecture Design document be there too?

**Comment by Noah-Moring** [comment]
Good catch

**Comment by Noah-Moring** [comment]
Should be there now

**Comment by BoppleOpple** [comment]
great! I cant think of anything else this deliverable, so I'm happy to call this all set!
